// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file was autogenerated. Please do not fix it manually
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedPropertyInspection"
#pragma ide diagnostic ignored "OCUnusedClassInspection"
#import "ASStyleObject.h"

@class ASStylerTextAttributes;
@class ASEXHelloLabelStyle;
@class ASEXHelloLabelTextAttributesStyle;
@class ASEXStyle;
@class ASEXWindowStyle;


@interface ASEXHelloLabelStyle : ASStyleObject <NSCoding, ASStyleObjectApplyable>
    - (id)initWithReloadedCallback:(void (^)())aCallback;

    @property (nonatomic) NSString *text;
@end

@interface ASEXHelloLabelTextAttributesStyle : ASStyleObject <NSCoding, ASStyleObjectApplyable>
    - (id)initWithReloadedCallback:(void (^)())aCallback;

    @property (nonatomic) NSTextAlignment alignment;
    @property (nonatomic) UIColor *color;
    @property (nonatomic) UIFont *font;
@end

@interface ASEXStyle : ASStyleObject <NSCoding, ASStyleObjectApplyable>
    - (id)initWithReloadedCallback:(void (^)())aCallback;

    @property (nonatomic) ASEXHelloLabelStyle *helloLabel;
    @property (nonatomic) ASEXWindowStyle *window;
    @property (nonatomic) ASStylerTextAttributes *helloLabelTextAttributes;
@end

@interface ASEXWindowStyle : ASStyleObject <NSCoding, ASStyleObjectApplyable>
    - (id)initWithReloadedCallback:(void (^)())aCallback;

    @property (nonatomic) BOOL keyboardIsDark;
    @property (nonatomic) UIColor *backgroundColor;
@end


#pragma clang diagnostic pop

